class qurandata {
  List<Map<String, String>> quranSurahs = [
    {"name": "Al-Fatiha", "arabic_name": "الفاتحة", "number_of_verses": "7"},
    {"name": "Al-Baqarah", "arabic_name": "البقرة", "number_of_verses": "286"},
    {
      "name": "Aal-E-Imran",
      "arabic_name": "آل عمران",
      "number_of_verses": "200",
    },
    {"name": "An-Nisa", "arabic_name": "النساء", "number_of_verses": "176"},
    {"name": "Al-Maidah", "arabic_name": "المائدة", "number_of_verses": "120"},
    {"name": "Al-Anam", "arabic_name": "الأنعام", "number_of_verses": "165"},
    {"name": "Al-Araf", "arabic_name": "الأعراف", "number_of_verses": "206"},
    {"name": "Al-Anfal", "arabic_name": "الأنفال", "number_of_verses": "75"},
    {"name": "At-Tawbah", "arabic_name": "التوبة", "number_of_verses": "129"},
    {"name": "Yunus", "arabic_name": "يونس", "number_of_verses": "109"},
    {"name": "Hud", "arabic_name": "هود", "number_of_verses": "123"},
    {"name": "Yusuf", "arabic_name": "يوسف", "number_of_verses": "111"},
    {"name": "Ar-Rad", "arabic_name": "الرعد", "number_of_verses": "43"},
    {"name": "Ibrahim", "arabic_name": "إبراهيم", "number_of_verses": "52"},
    {"name": "Al-Hijr", "arabic_name": "الحجر", "number_of_verses": "99"},
    {"name": "An-Nahl", "arabic_name": "النحل", "number_of_verses": "128"},
    {"name": "Al-Isra", "arabic_name": "الإسراء", "number_of_verses": "111"},
    {"name": "Al-Kahf", "arabic_name": "الكهف", "number_of_verses": "110"},
    {"name": "Maryam", "arabic_name": "مريم", "number_of_verses": "98"},
    {"name": "Ta-Ha", "arabic_name": "طه", "number_of_verses": "135"},
    {"name": "Al-Anbiya", "arabic_name": "الأنبياء", "number_of_verses": "112"},
    {"name": "Al-Hajj", "arabic_name": "الحج", "number_of_verses": "78"},
    {
      "name": "Al-Muminun",
      "arabic_name": "المؤمنون",
      "number_of_verses": "118",
    },
    {"name": "An-Nur", "arabic_name": "النور", "number_of_verses": "64"},
    {"name": "Al-Furqan", "arabic_name": "الفرقان", "number_of_verses": "77"},
    {
      "name": "Ash-Shu'ara",
      "arabic_name": "الشعراء",
      "number_of_verses": "227",
    },
    {"name": "An-Naml", "arabic_name": "النمل", "number_of_verses": "93"},
    {"name": "Al-Qasas", "arabic_name": "القصص", "number_of_verses": "88"},
    {"name": "Al-Ankabut", "arabic_name": "العنكبوت", "number_of_verses": "69"},
    {"name": "Ar-Rum", "arabic_name": "الروم", "number_of_verses": "60"},
    {"name": "Luqman", "arabic_name": "لقمان", "number_of_verses": "34"},
    {"name": "As-Sajda", "arabic_name": "السجدة", "number_of_verses": "30"},
    {"name": "Al-Ahzab", "arabic_name": "الأحزاب", "number_of_verses": "73"},
    {"name": "Saba", "arabic_name": "سبأ", "number_of_verses": "54"},
    {"name": "Fatir", "arabic_name": "فاطر", "number_of_verses": "45"},
    {"name": "Ya-Sin", "arabic_name": "يس", "number_of_verses": "83"},
    {"name": "As-Saffat", "arabic_name": "الصافات", "number_of_verses": "182"},
    {"name": "Sad", "arabic_name": "ص", "number_of_verses": "88"},
    {"name": "Az-Zumar", "arabic_name": "الزمر", "number_of_verses": "75"},
    {"name": "Ghafir", "arabic_name": "غافر", "number_of_verses": "85"},
    {"name": "Fussilat", "arabic_name": "فصلت", "number_of_verses": "54"},
    {"name": "Ash-Shura", "arabic_name": "الشورى", "number_of_verses": "53"},
    {"name": "Az-Zukhruf", "arabic_name": "الزخرف", "number_of_verses": "89"},
    {"name": "Ad-Dukhan", "arabic_name": "الدخان", "number_of_verses": "59"},
    {"name": "Al-Jathiya", "arabic_name": "الجاثية", "number_of_verses": "37"},
    {"name": "Al-Ahqaf", "arabic_name": "الأحقاف", "number_of_verses": "35"},
    {"name": "Muhammad", "arabic_name": "محمد", "number_of_verses": "38"},
    {"name": "Al-Fath", "arabic_name": "الفتح", "number_of_verses": "29"},
    {"name": "Al-Hujraat", "arabic_name": "الحجرات", "number_of_verses": "18"},
    {"name": "Qaf", "arabic_name": "ق", "number_of_verses": "45"},
    {
      "name": "Adh-Dhariyat",
      "arabic_name": "الذاريات",
      "number_of_verses": "60",
    },
    {"name": "At-Tur", "arabic_name": "الطور", "number_of_verses": "49"},
    {"name": "An-Najm", "arabic_name": "النجم", "number_of_verses": "62"},
    {"name": "Al-Qamar", "arabic_name": "القمر", "number_of_verses": "55"},
    {"name": "Ar-Rahman", "arabic_name": "الرحمن", "number_of_verses": "78"},
    {"name": "Al-Waqia", "arabic_name": "الواقعة", "number_of_verses": "96"},
    {"name": "Al-Hadid", "arabic_name": "الحديد", "number_of_verses": "29"},
    {
      "name": "Al-Mujadila",
      "arabic_name": "المجادلة",
      "number_of_verses": "22",
    },
    {"name": "Al-Hashr", "arabic_name": "الحشر", "number_of_verses": "24"},
    {
      "name": "Al-Mumtahina",
      "arabic_name": "الممتحنة",
      "number_of_verses": "13",
    },
    {"name": "As-Saff", "arabic_name": "الصف", "number_of_verses": "14"},
    {"name": "Al-Jumu'a", "arabic_name": "الجمعة", "number_of_verses": "11"},
    {
      "name": "Al-Munafiqun",
      "arabic_name": "المنافقون",
      "number_of_verses": "11",
    },
    {"name": "At-Taghabun", "arabic_name": "التغابن", "number_of_verses": "18"},
    {"name": "At-Talaq", "arabic_name": "الطلاق", "number_of_verses": "12"},
    {"name": "At-Tahrim", "arabic_name": "التحريم", "number_of_verses": "12"},
    {"name": "Al-Mulk", "arabic_name": "الملك", "number_of_verses": "30"},
    {"name": "Al-Qalam", "arabic_name": "القلم", "number_of_verses": "52"},
    {"name": "Al-Haqqa", "arabic_name": "الحاقة", "number_of_verses": "52"},
    {"name": "Al-Maarij", "arabic_name": "المعارج", "number_of_verses": "44"},
    {"name": "Nuh", "arabic_name": "نوح", "number_of_verses": "28"},
    {"name": "Al-Jinn", "arabic_name": "الجن", "number_of_verses": "28"},
    {"name": "Al-Muzzammil", "arabic_name": "المزمل", "number_of_verses": "20"},
    {"name": "Al-Muddathir", "arabic_name": "المدثر", "number_of_verses": "56"},
    {"name": "Al-Qiyama", "arabic_name": "القيامة", "number_of_verses": "40"},
    {"name": "Al-Insan", "arabic_name": "الإنسان", "number_of_verses": "31"},
    {
      "name": "Al-Mursalat",
      "arabic_name": "المرسلات",
      "number_of_verses": "50",
    },
    {"name": "An-Naba", "arabic_name": "النبأ", "number_of_verses": "40"},
    {"name": "An-Nazi'at", "arabic_name": "النازعات", "number_of_verses": "46"},
    {"name": "Abasa", "arabic_name": "عبس", "number_of_verses": "42"},
    {"name": "At-Takwir", "arabic_name": "التكوير", "number_of_verses": "29"},
    {"name": "Al-Infitar", "arabic_name": "الانفطار", "number_of_verses": "19"},
    {
      "name": "Al-Mutaffifin",
      "arabic_name": "المطففين",
      "number_of_verses": "36",
    },
    {
      "name": "Al-Inshiqaq",
      "arabic_name": "الانشقاق",
      "number_of_verses": "25",
    },
    {"name": "Al-Buruj", "arabic_name": "البروج", "number_of_verses": "22"},
    {"name": "At-Tariq", "arabic_name": "الطارق", "number_of_verses": "17"},
    {"name": "Al-Ala", "arabic_name": "الأعلى", "number_of_verses": "19"},
    {"name": "Al-Ghashiya", "arabic_name": "الغاشية", "number_of_verses": "26"},
    {"name": "Al-Fajr", "arabic_name": "الفجر", "number_of_verses": "30"},
    {"name": "Al-Balad", "arabic_name": "البلد", "number_of_verses": "20"},
    {"name": "Ash-Shams", "arabic_name": "الشمس", "number_of_verses": "15"},
    {"name": "Al-Lail", "arabic_name": "الليل", "number_of_verses": "21"},
    {"name": "Ad-Duhaa", "arabic_name": "الضحى", "number_of_verses": "11"},
    {"name": "Ash-Sharh", "arabic_name": "الشرح", "number_of_verses": "8"},
    {"name": "At-Tin", "arabic_name": "التين", "number_of_verses": "8"},
    {"name": "Al-Alaq", "arabic_name": "العلق", "number_of_verses": "19"},
    {"name": "Al-Qadr", "arabic_name": "القدر", "number_of_verses": "5"},
    {"name": "Al-Bayyina", "arabic_name": "البينة", "number_of_verses": "8"},
    {"name": "Az-Zalzala", "arabic_name": "الزلزلة", "number_of_verses": "8"},
    {"name": "Al-Adiyat", "arabic_name": "العاديات", "number_of_verses": "11"},
    {"name": "Al-Qaria", "arabic_name": "القارعة", "number_of_verses": "11"},
    {"name": "At-Takathur", "arabic_name": "التكاثر", "number_of_verses": "8"},
    {"name": "Al-Asr", "arabic_name": "العصر", "number_of_verses": "3"},
    {"name": "Al-Humaza", "arabic_name": "الهمزة", "number_of_verses": "9"},
    {"name": "Al-Fil", "arabic_name": "الفيل", "number_of_verses": "5"},
    {"name": "Quraish", "arabic_name": "قريش", "number_of_verses": "4"},
    {"name": "Al-Maun", "arabic_name": "الماعون", "number_of_verses": "7"},
    {"name": "Al-Kawthar", "arabic_name": "الكوثر", "number_of_verses": "3"},
    {"name": "Al-Kafiroon", "arabic_name": "الكافرون", "number_of_verses": "6"},
    {"name": "An-Nasr", "arabic_name": "النصر", "number_of_verses": "3"},
    {"name": "Al-Masad", "arabic_name": "المسد", "number_of_verses": "5"},
    {"name": "Al-Ikhlas", "arabic_name": "الإخلاص", "number_of_verses": "4"},
    {"name": "Al-Falaq", "arabic_name": "الفلق", "number_of_verses": "5"},
    {"name": "An-Nas", "arabic_name": "الناس", "number_of_verses": "6"},
  ];
}
